src/HowAngryTwitter/Models/MCSBodyPOST.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HowAngryTwitter.Models
{
    public class Document
    {
        public string language { get; set; }
        public string id { get; set; }
        public string text { get; set; }
    }

    public class MCSBodyPOST
    {
        public List<Document> documents { get; set; }
    }
}

src/HowAngryTwitter/Models/MCSLanguagesResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HowAngryTwitter.Models
{
    public class DetectedLanguage
    {
        public string name { get; set; }
        public string iso6391Name { get; set; }
        public double score { get; set; }
    }

    public class LanguageDocument
    {
        public string id { get; set; }
        public List<DetectedLanguage> detectedLanguages { get; set; }
    }

    public class MCSLanguagesResponse
    {
        public List<LanguageDocument> documents { get; set; }
        public List<object> errors { get; set; }
    }
}

src/HowAngryTwitter/Models/MCSSentimentResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HowAngryTwitter.Models
{
    public class SentimentDocument
    {
        public double score { get; set; }
        public string id { get; set; }
    }

    public class MCSSentimentResponse
    {
        public List<SentimentDocument> documents { get; set; }
        public List<object> errors { get; set; }
    }
}

src/HowAngryTwitter/Models/TwitterTimeline.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HowAngryTwitter.Models
{
    public class TwitterTimeline
    {
        public string created_at { get; set; }
        public object id { get; set; }
        public string id_str { get; set; }
        public string text { get; set; }
        // more useless properties...

        public string language { get; set; }
    }
}

src/HowAngryTwitter/Controllers/AngryTwitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using Newtonsoft.Json.Linq;

/*
 * 
 * Esta nueva clase Controller es accesible en la Web poniendo /AngryTwitter para el Index() y /AngryTwitter/Welcome para el Welcome()
 * La ruta root de la Web sigue utilizando el Controller HomeController porque es lo que está definido en la clase Startup.cs (al final):
 * app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
 * 
 */

namespace HowAngryTwitter.Controllers
{
    public class AngryTwitterController : Controller
    {
        // GET: /AngryTwitter/

        public IActionResult Index()
        {
            return View();
        }

        // GET: /AngryTwitter/
        [HttpPost]
        public ActionResult Index(string username)
        {
            // Redirijo a la vista de resultados pasando como parámetro al usuario de Twitter!
            return RedirectToAction("TwitterResult", new { user = username });  // redirecting to another view
        }

        // GET: /AngryTwitter/Welcome/ 

        public IActionResult Welcome(string name)
        {
            ViewData["Name"] = name;

            return View();
        }

        // GET: /AngryTwitter/About

        public IActionResult About()
        {
            return View();
        }

        // GET: /AngryTwitter/Contact

        public IActionResult Contact()
        {
            return View();
        }

        // GET: /AngryTwitter/TwitterResult

        public async Task<ActionResult> TwitterResult(string user)
        {
            // Aquí se hace el trabajo, antes de devolver la Vista con el % de Angry Tweets

            ViewBag.SyncOrAsync = "Asynchronous";
            var _service = new Services.NetworkServices();

            // Obtenemos el Timeline de Tweets de TWITTER API
            List<Models.TwitterTimeline> TwitterList = await _service.GetTimelineTwitter(user);

            //Construyo un objeto JSON complejo para enviar a la API de Lenguaje de MCS
            JArray arrayRoot = new JArray();

            foreach (var item in TwitterList)
            {
                JObject o = JObject.FromObject(
                        new Models.Document
                        {
                            id = item.id_str,
                            text = item.text
                        }
                    );

                arrayRoot.Add(o);
            }
            
            JObject objectRoot = new JObject();
            objectRoot["documents"] = arrayRoot;
            
            // Obtenemos la lista de los Lenguajes correspondientes a cada Tweet mediante la API de Lenguaje de MCS
            string json = objectRoot.ToString();
            List<Models.LanguageDocument> LanguageDocumentsList = await _service.PostTimelineLanguages(TwitterList, json);

            var join = from twitter in TwitterList
                       from languages in LanguageDocumentsList
                       where twitter.id_str == languages.id
                       select new { Lang = languages.detectedLanguages.First().iso6391Name, TID = twitter.id_str, LID = languages.id };

            foreach (var item in TwitterList)
            {
                string language = join.FirstOrDefault(x => x.LID == item.id_str).Lang;
                item.language = language;
            }

            //
            // Obtenemos la lista de Emociones de cada Tweet del Timeline mediante la API de Emociones de MCS
            ///////

            //Construyo un objeto JSON complejo para enviar a la API de Lenguaje de MCS
            arrayRoot = new JArray();

            foreach (var item in TwitterList)
            {
                JObject o = JObject.FromObject(
                        new Models.Document
                        {
                            id = item.id_str,
                            text = item.text
                        }
                    );

                arrayRoot.Add(o);
            }

            objectRoot = new JObject();
            objectRoot["documents"] = arrayRoot;
            json = objectRoot.ToString();

            List<Models.SentimentDocument> SentimentalList = await _service.PostTimelineEmotions(TwitterList, json);

            double angryPercentage = 0;
            double angryTotalSum = 0;
            foreach (var item in SentimentalList)
            {
                angryTotalSum += item.score;
            }
            angryPercentage = angryTotalSum / SentimentalList.Count * 100;

            ViewData["AngryPercentage"] = string.Format("{0:0.00}", angryPercentage);

            return View("TwitterResult", await _service.GetTimelineTwitter(user));
        }
    }
}

src/HowAngryTwitter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HowAngryTwitter.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/HowAngryTwitter/Views/AngryTwitter/About.cshtml
@*
    Al hacer un return view(); en el método Index del AngryTwitterController, por defecto busca un fichero .cshtml en /Views/AngryTwitter que será lo que devuelva
*@

@{
    ViewData["Title"] = "About";
}

<h2>About</h2>

<p>Hello from our View Template!</p>

src/HowAngryTwitter/Views/AngryTwitter/Contact.cshtml
@*
    Al hacer un return view(); en el método Index del AngryTwitterController, por defecto busca un fichero .cshtml en /Views/AngryTwitter que será lo que devuelva
*@

@{
    ViewData["Title"] = "Contact";
}

<h2>Contact</h2>

<p>Hello from our View Template!</p>

src/HowAngryTwitter/Views/AngryTwitter/Index.cshtml
@*
    Al hacer un return view(); en el método Index del AngryTwitterController, por defecto busca un fichero .cshtml en /Views/AngryTwitter que será lo que devuelva
*@

@{
    ViewData["Title"] = "How Angry Twitter";
}

<div class="jumbotron">
    <h1>How angry are you on Twitter?</h1>
    <p class="lead">This small tool analyzes your tweets using the Microsoft Cognitive Services and the Twitter API with Application-only authentication.</p>

    <br />
    <br />
    <br />
    <br />

        @using (Html.BeginForm())
        {
            <input type="text" name="username" />
            <input type="submit"  class="btn btn-info" value="Analyze my tweets" />
        }
    
</div>

src/HowAngryTwitter/Views/AngryTwitter/TwitterResult.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Analyze Results";
}

<h1>Twitter Analyze Results</h1>

<h2> @ViewData["AngryPercentage"] % of your tweets are angry.</h2>

src/HowAngryTwitter/Views/AngryTwitter/Welcome.cshtml
@*
    Al hacer un return view(); en el método Welcome del AngryTwitterController, por defecto busca un fichero .cshtml con el mismo nombre en /Views/AngryTwitter que será lo que devuelva
*@

@{
    ViewData["Title"] = "Welcome";
}

<h2>Wecolme</h2>

<p>WELCOME @ViewData["Name"] from our View Template!</p>

src/HowAngryTwitter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - How Angry Twitter</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="AngryTwitter" asp-action="Index" class="navbar-brand">How Angry Twitter</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="AngryTwitter" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="AngryTwitter" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="AngryTwitter" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - HowAngryTwitter</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>